// Mocks generated by Mockito 5.4.4 from annotations
// in frontend_flutter_pos/test/cart_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend_flutter_pos/pos/models/cart_model.dart' as _i2;
import 'package:frontend_flutter_pos/pos/services/cart_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCart_0 extends _i1.SmartFake implements _i2.Cart {
  _FakeCart_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCartItem_1 extends _i1.SmartFake implements _i2.CartItem {
  _FakeCartItem_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CartService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartService extends _i1.Mock implements _i3.CartService {
  MockCartService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Cart> getCart(String? cartId) => (super.noSuchMethod(
        Invocation.method(
          #getCart,
          [cartId],
        ),
        returnValue: _i4.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #getCart,
            [cartId],
          ),
        )),
      ) as _i4.Future<_i2.Cart>);

  @override
  _i4.Future<_i2.Cart> addItemToCart(
    String? cartId,
    _i2.CartItem? item,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addItemToCart,
          [
            cartId,
            item,
          ],
        ),
        returnValue: _i4.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #addItemToCart,
            [
              cartId,
              item,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Cart>);

  @override
  _i4.Future<_i2.Cart> removeItemFromCart(
    String? cartId,
    int? itemId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeItemFromCart,
          [
            cartId,
            itemId,
          ],
        ),
        returnValue: _i4.Future<_i2.Cart>.value(_FakeCart_0(
          this,
          Invocation.method(
            #removeItemFromCart,
            [
              cartId,
              itemId,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Cart>);

  @override
  _i4.Future<_i2.CartItem> updateCartItem(
    String? cartId,
    int? itemId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateCartItem,
          [
            cartId,
            itemId,
            quantity,
          ],
        ),
        returnValue: _i4.Future<_i2.CartItem>.value(_FakeCartItem_1(
          this,
          Invocation.method(
            #updateCartItem,
            [
              cartId,
              itemId,
              quantity,
            ],
          ),
        )),
      ) as _i4.Future<_i2.CartItem>);

  @override
  _i4.Future<void> clearCart(String? cartId) => (super.noSuchMethod(
        Invocation.method(
          #clearCart,
          [cartId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> checkoutCart(String? cartId) => (super.noSuchMethod(
        Invocation.method(
          #checkoutCart,
          [cartId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
